server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/ssmtest?characterEncoding=utf8
        username: root
        password: root
         # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        maxPoolPreparedStatementPerConnectionSize: 20
        #filters: stat,wall,log4j
    ##这里加个注释：本来的model是html5解析的，但是由于模板严格的解析，导致页面中所有的标签都需要有结束标签，非常麻烦，再次修改一下
    thymeleaf:
      mode: LEGACYHTML5
      cache: false

## 该配置节点为独立的节点，有很多人容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zzj.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#配置日志
logging:
  path: E:/logs/demo
  #配置日志文件路径